#!/usr/bin/env python3
"""
B112 - Git status hygiene via local exclude

Purpose
-------
Reduce noisy `git status --short` output by adding local-only ignore rules to
`.git/info/exclude`.

This is intentionally local:
- It does not modify `.gitignore`
- It does not affect other collaborators
- It does not delete files
- It does not modify website files, maps or data
- It makes accidental staging of raw/working/LGL test files less likely

Use this after the FIONA-based Oberschwaben public story was restored and
stabilized.

Changed files
-------------
- .git/info/exclude
- docs/B112_git_status_hygiene_local_exclude.md
- docs/B112_git_status_hygiene_local_exclude_audit.txt
- tasks/done.md

Not changed
-----------
- index.html
- src/styles.css
- public/maps/*
- data/*
- any raw/working files
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
GIT_EXCLUDE = ROOT / ".git" / "info" / "exclude"
DOCS = ROOT / "docs"
TASKS = ROOT / "tasks"
DONE = TASKS / "done.md"

REPORT = DOCS / "B112_git_status_hygiene_local_exclude.md"
AUDIT = DOCS / "B112_git_status_hygiene_local_exclude_audit.txt"

BLOCK_START = "# B112_LOCAL_WORKTREE_HYGIENE_START"
BLOCK_END = "# B112_LOCAL_WORKTREE_HYGIENE_END"

LOCAL_EXCLUDE_PATTERNS = [
    "",
    BLOCK_START,
    "# Local project hygiene only. Do not commit raw/working/probe material.",
    "# Generated by scripts/112_git_status_hygiene_local_exclude.py.",
    "",
    "# local backups / handoff bundles",
    "_backup_before_clean_pre105_restore/",
    "_handoff_oberschwaben_restore/",
    "_handoff_oberschwaben_restore.zip",
    "handoff_restore/",
    "",
    "# raw / working GIS and temporary material",
    "data/external/",
    "data/working/",
    "working/",
    "sources/",
    "design_dummies/",
    "",
    "# parked LGL public-test map outputs",
    "public/maps/oberschwaben_lgl/",
    "public/maps/oberschwaben_lgl_arcgis/",
    "",
    "# generated/local metadata that should not be staged without review",
    "data/metadata/peat_soils_source_catalog.csv",
    "",
    "# parked LGL/FIONA probe scripts after decision to continue with FIONA story",
    "scripts/105_source_swap_plan_and_fiona_safety_mode.py",
    "scripts/105r_restore_fiona_public_story_state.py",
    "scripts/106_candidate_source_probe.py",
    "scripts/107_lgl_landnutzung_schema_and_oberschwaben_sample.py",
    "scripts/107b_lgl_landnutzung_grid_class_universe_probe.py",
    "scripts/107c_lgl_landnutzung_mapping_review.py",
    "scripts/108_lgl_landnutzung_controlled_production_test.py",
    "scripts/108b_lgl_dissolve_cartographic_layers.py",
    "scripts/109a_arcgis_lgl_oberschwaben_restyle_brief.py",
    "",
    "# parked FIONA direct-access probes / download experiments",
    "scripts/95c_download_fiona_2024_wfs_bbox.py",
    "scripts/95d_probe_fiona_wfs_direct_access.py",
    "scripts/95e_download_fiona_wfs_with_proxy_params.py",
    "scripts/95f_probe_fiona_wfs_post_namespace.py",
    "scripts/95g_fix_fiona_wfs_projection_and_clip.py",
    "",
    "# parked LGL/FIONA probe documentation and generated QA material",
    "docs/B105_candidate_source_matrix.md",
    "docs/B105_fiona_public_safety_audit.txt",
    "docs/B105_source_swap_plan_and_fiona_safety_mode.md",
    "docs/B105r_restore_fiona_public_story_audit.txt",
    "docs/B105r_restore_fiona_public_story_state.md",
    "docs/B106_*",
    "docs/B107_*",
    "docs/B107b_*",
    "docs/B107c_*",
    "docs/B108_*",
    "docs/B108b_*",
    "docs/B109a_*",
    "",
    "# generated audit extracts; keep out unless deliberately publishing audit internals",
    "docs/B103_visible_text_extract.txt",
    "docs/B103_public_text_findings.csv",
    "docs/B103_wording_frequency.csv",
    "docs/B103b_visible_text_extract_corrected.txt",
    "docs/B103b_hidden_retired_text_extract.txt",
    "docs/B103b_visible_findings.csv",
    "docs/B103b_hidden_findings.csv",
    "docs/B103b_wording_frequency.csv",
    "docs/B104_visible_wording_polish_audit.txt",
    "docs/B104b_second_visible_wording_and_oberschwaben_density_audit.txt",
    "",
    BLOCK_END,
    "",
]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def run_git_status() -> list[str]:
    try:
        completed = subprocess.run(
            ["git", "status", "--short"],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        out = completed.stdout.strip("\n")
        return out.splitlines() if out else []
    except Exception as exc:
        return [f"ERROR running git status: {exc}"]


def replace_block(existing: str, block: str) -> tuple[str, str]:
    start = existing.find(BLOCK_START)
    end = existing.find(BLOCK_END)

    if start >= 0 and end >= start:
        end2 = end + len(BLOCK_END)
        # Include trailing line break if present.
        if end2 < len(existing) and existing[end2:end2 + 2] == "\r\n":
            end2 += 2
        elif end2 < len(existing) and existing[end2:end2 + 1] == "\n":
            end2 += 1
        new_text = existing[:start].rstrip() + "\n" + block + "\n" + existing[end2:].lstrip()
        return new_text.rstrip() + "\n", "updated existing B112 block"

    new_text = existing.rstrip() + "\n" + block + "\n"
    return new_text, "appended B112 block"


def classify_status(lines: list[str]) -> dict[str, int]:
    categories = {
        "total": len(lines),
        "backup_handoff": 0,
        "raw_working_data": 0,
        "parked_lgl_or_fiona_probe": 0,
        "generated_audit_extracts": 0,
        "source_register_or_release_docs": 0,
        "other": 0,
    }

    for line in lines:
        path = line[3:] if len(line) > 3 else line
        p = path.replace("\\", "/")

        if p.startswith("_backup_") or p.startswith("_handoff_") or p.startswith("handoff_restore/"):
            categories["backup_handoff"] += 1
        elif p.startswith("data/external/") or p.startswith("data/working/") or p.startswith("working/") or p.startswith("sources/") or p.startswith("design_dummies/"):
            categories["raw_working_data"] += 1
        elif (
            p.startswith("public/maps/oberschwaben_lgl/")
            or p.startswith("scripts/106_")
            or p.startswith("scripts/107")
            or p.startswith("scripts/108")
            or p.startswith("scripts/109a")
            or p.startswith("scripts/95")
            or p.startswith("docs/B106")
            or p.startswith("docs/B107")
            or p.startswith("docs/B108")
            or p.startswith("docs/B109a")
            or p.startswith("docs/B105")
        ):
            categories["parked_lgl_or_fiona_probe"] += 1
        elif (
            p.startswith("docs/B103")
            or p.startswith("docs/B104")
        ) and (
            "extract" in p or "findings" in p or "frequency" in p or "audit" in p
        ):
            categories["generated_audit_extracts"] += 1
        elif p.startswith("docs/B110") or p.startswith("scripts/110") or p.startswith("docs/B112") or p.startswith("scripts/112"):
            categories["source_register_or_release_docs"] += 1
        else:
            categories["other"] += 1

    return categories


def update_done() -> None:
    current = read_text(DONE) if DONE.exists() else "# Done\n"
    marker = "## B112 - Git status hygiene via local exclude"
    if marker in current:
        return
    entry = f"""
## B112 - Git status hygiene via local exclude ({date.today().isoformat()})

- Added local `.git/info/exclude` rules for backup bundles, raw/working data, parked LGL/FIONA probe material and generated audit extracts.
- Did not modify public page files, maps, raw data or `.gitignore`.
- Kept the hygiene rules local to this working copy.
"""
    write_text(DONE, current.rstrip() + "\n" + entry)


def main() -> None:
    if not (ROOT / ".git").exists():
        print("This does not look like a git repository root.")
        sys.exit(1)

    DOCS.mkdir(exist_ok=True)
    TASKS.mkdir(exist_ok=True)
    GIT_EXCLUDE.parent.mkdir(parents=True, exist_ok=True)

    before_lines = run_git_status()
    before = classify_status(before_lines)

    existing = read_text(GIT_EXCLUDE) if GIT_EXCLUDE.exists() else ""
    block = "\n".join(LOCAL_EXCLUDE_PATTERNS).strip() + "\n"
    new_text, mode = replace_block(existing, block)
    write_text(GIT_EXCLUDE, new_text)

    after_lines = run_git_status()
    after = classify_status(after_lines)

    update_done()

    report = [
        "# B112 - Git Status Hygiene via Local Exclude",
        "",
        f"Date: {date.today().isoformat()}",
        "",
        "## Result",
        "",
        f"B112 {mode} in `.git/info/exclude`.",
        "",
        "This is local hygiene only. No website files, map files, data files or `.gitignore` were changed.",
        "",
        "## Why",
        "",
        "The working tree contained many parked raw/working/probe files. Keeping them visible in `git status` increases the risk of accidentally staging raw GIS data, LGL test layers, backup bundles or generated audit extracts.",
        "",
        "## Git status counts",
        "",
        "| Category | Before | After |",
        "|---|---:|---:|",
    ]

    for key in before:
        report.append(f"| {key} | {before[key]} | {after.get(key, 0)} |")

    report.extend([
        "",
        "## Local exclude block",
        "",
        "```gitignore",
        block.strip(),
        "```",
        "",
        "## Important",
        "",
        "- `.git/info/exclude` is not committed.",
        "- This does not delete or move any local files.",
        "- Use explicit `git add <file>` for future commits.",
        "- Do not use `git add .`.",
        "",
    ])
    write_text(REPORT, "\n".join(report))

    audit = [
        "# B112 audit",
        "",
        f"- Mode: {mode}",
        f"- Git status lines before: {before['total']}",
        f"- Git status lines after: {after['total']}",
        f"- Raw/working-like lines after: {after['raw_working_data']}",
        f"- Parked LGL/FIONA-probe lines after: {after['parked_lgl_or_fiona_probe']}",
        "",
        "## Remaining status lines after B112",
        "",
    ]

    if after_lines:
        audit.append("```text")
        audit.extend(after_lines[:200])
        if len(after_lines) > 200:
            audit.append(f"... truncated, {len(after_lines) - 200} more lines")
        audit.append("```")
    else:
        audit.append("No remaining git status lines.")

    audit.extend([
        "",
        "## Recommended next commands",
        "",
        "```powershell",
        "git status --short",
        "python scripts\\58_visual_qa_and_commit_check.py",
        "```",
        "",
    ])
    write_text(AUDIT, "\n".join(audit))

    print("B112 git status hygiene complete.")
    print("Changed/created:")
    for p in [GIT_EXCLUDE, REPORT, AUDIT, DONE]:
        print(f"  {rel(p)}")
    print("")
    print(f"Git status lines before: {before['total']}")
    print(f"Git status lines after:  {after['total']}")
    print("")
    print("Review:")
    print("  Get-Content docs\\B112_git_status_hygiene_local_exclude_audit.txt")
    print("  git status --short")
    print("")
    print("Do not commit .git/info/exclude; it is local by design.")


if __name__ == "__main__":
    main()
